// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "プロセスの liveness を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerStatusResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "依存サービスの readiness を返します。未準備の場合は 503 を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerStatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerStatusResponse"
                        }
                    }
                }
            }
        },
        "/v1/account": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中の共有アカウント本体と、この identity が接続している app membership 一覧を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Current shared account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerAccountOverviewResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/account/apps/{appID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在の共有アカウントから指定 app との membership を解除します。identity 本体は削除しません。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Disconnect app from current account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/account/deletion": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在の shared account に対する削除予約状態を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Get account deletion request",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerDeletionRequestEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在の shared account の完全削除を予約します。app membership だけでなく identity 本体が対象です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Schedule shared account deletion",
                "parameters": [
                    {
                        "description": "deletion request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.swaggerScheduleDeletionRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerDeletionRequestEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "予約済み shared account deletion を取り消します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Cancel shared account deletion",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/apps": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登録済みアプリ一覧を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Apps"
                ],
                "summary": "List apps",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerAppListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "app を作成します。` + "`" + `client` + "`" + ` ブロックまたは ` + "`" + `redirect_uris` + "`" + ` を指定すると OIDC client も同時作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Apps"
                ],
                "summary": "Create app",
                "parameters": [
                    {
                        "description": "app creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.swaggerCreateAppRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerCreateAppWithClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/apps/{appID}/clients": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定 app に紐づく OIDC client 一覧を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Apps"
                ],
                "summary": "List OIDC clients",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerOIDCClientListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定 app 向けに OIDC client を作成します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Apps"
                ],
                "summary": "Create OIDC client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "OIDC client creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.swaggerCreateOIDCClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerCreateOIDCClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/apps/{appID}/management-token": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "app-scoped user management API 用の management token を発行します。既存 token は無効化されます。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Apps"
                ],
                "summary": "Issue or rotate app management token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App ID",
                        "name": "appID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerManagementTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/audit-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "actor / target / event type と pagination で監査ログを取得します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Audit"
                ],
                "summary": "List audit logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "actor type",
                        "name": "actor_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "actor id",
                        "name": "actor_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "target type",
                        "name": "target_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "target id",
                        "name": "target_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "event type",
                        "name": "event_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerAuditLogListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Kratos identity を identifier と state で検索します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Search users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email / phone partial match",
                        "name": "identifier",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "active",
                            "inactive"
                        ],
                        "type": "string",
                        "description": "identity state",
                        "name": "state",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerIdentityListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{userRef}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "identity を削除します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identity UUID or URL-encoded email",
                        "name": "userRef",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "` + "`" + `state` + "`" + ` と ` + "`" + `roles` + "`" + ` のどちらか、または両方を更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Patch user state or roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identity UUID or URL-encoded email",
                        "name": "userRef",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "patch user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.swaggerPatchUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerRolesUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/admin/users/{userRef}/revoke-sessions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "identity に紐づくアクティブセッションを失効します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin Users"
                ],
                "summary": "Revoke user sessions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identity UUID or URL-encoded email",
                        "name": "userRef",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/apps/self/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "app management token に紐づく app から見える membership 一覧を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App Self"
                ],
                "summary": "List app-scoped users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerMembershipListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/apps/self/users/{identityID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "app management token に紐づく app から指定 identity の membership を無効化します。shared account 本体は削除しません。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App Self"
                ],
                "summary": "Revoke app-scoped user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identity ID",
                        "name": "identityID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/consent": {
            "get": {
                "description": "first-party や skip consent の場合は自動 accept、確認が必要な場合は HTML を返します。",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Hydra consent challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hydra consent challenge",
                        "name": "consent_challenge",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "HTML consent page",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "HTML consent 画面の submit 先です。CSRF Cookie と csrf_token の一致が必要です。",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Submit consent decision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hydra consent challenge",
                        "name": "consent_challenge",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF token",
                        "name": "csrf_token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "accept",
                            "deny"
                        ],
                        "type": "string",
                        "description": "accept or deny",
                        "name": "action",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/login": {
            "get": {
                "description": "Hydra の login_challenge を処理し、Kratos login/settings か Hydra accept へリダイレクトします。",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Hydra login challenge",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hydra login challenge",
                        "name": "login_challenge",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "get": {
                "description": "` + "`" + `logout_challenge` + "`" + ` がなければ logout URL を返すか Hydra へリダイレクトし、あれば Hydra の logout callback を処理します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hydra logout challenge",
                        "name": "logout_challenge",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerLogoutStartResponse"
                        }
                    },
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "303": {
                        "description": "See Other",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Accept ヘッダーに応じて logout URL の JSON 返却またはブラウザリダイレクトを返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout start",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerLogoutStartResponse"
                        }
                    },
                    "303": {
                        "description": "See Other",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/auth/providers": {
            "get": {
                "description": "Kratos / Hydra の browser flow URL 一覧を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Browser flow provider URLs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.ProviderView"
                        }
                    }
                }
            }
        },
        "/v1/auth/session": {
            "get": {
                "description": "現在の Kratos セッション要約を返します。未認証でも 200 で ` + "`" + `authenticated=false` + "`" + ` を返します。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Current session",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.SessionView"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/theme": {
            "post": {
                "description": "推しメンカラー設定を更新します。Kratos セッション Cookie が必要です。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Update theme preference",
                "parameters": [
                    {
                        "description": "theme preference",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.swaggerThemePreferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/http.swaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.App": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "party_type": {
                    "$ref": "#/definitions/app.PartyType"
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/app.AppStatus"
                },
                "type": {
                    "$ref": "#/definitions/app.AppType"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "app.AppStatus": {
            "type": "string",
            "enum": [
                "active",
                "disabled"
            ],
            "x-enum-varnames": [
                "AppStatusActive",
                "AppStatusDisabled"
            ]
        },
        "app.AppType": {
            "type": "string",
            "enum": [
                "web",
                "spa",
                "native",
                "m2m"
            ],
            "x-enum-varnames": [
                "AppTypeWeb",
                "AppTypeSPA",
                "AppTypeNative",
                "AppTypeM2M"
            ]
        },
        "app.ClientStatus": {
            "type": "string",
            "enum": [
                "active",
                "disabled",
                "rotated"
            ],
            "x-enum-varnames": [
                "ClientStatusActive",
                "ClientStatusDisabled",
                "ClientStatusRotated"
            ]
        },
        "app.ClientType": {
            "type": "string",
            "enum": [
                "public",
                "confidential"
            ],
            "x-enum-varnames": [
                "ClientTypePublic",
                "ClientTypeConfidential"
            ]
        },
        "app.OIDCClient": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "client_type": {
                    "$ref": "#/definitions/app.ClientType"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "hydra_client_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "pkce_required": {
                    "type": "boolean"
                },
                "post_logout_redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "status": {
                    "$ref": "#/definitions/app.ClientStatus"
                },
                "token_endpoint_auth_method": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "app.PartyType": {
            "type": "string",
            "enum": [
                "first_party",
                "third_party"
            ],
            "x-enum-varnames": [
                "PartyTypeFirst",
                "PartyTypeThird"
            ]
        },
        "http.ProviderView": {
            "type": "object",
            "properties": {
                "login_url": {
                    "type": "string"
                },
                "logout_url": {
                    "type": "string"
                },
                "recovery_url": {
                    "type": "string"
                },
                "registration_url": {
                    "type": "string"
                },
                "settings_url": {
                    "type": "string"
                },
                "verification_url": {
                    "type": "string"
                }
            }
        },
        "http.SessionView": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "authenticator_assurance_level": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "identity_id": {
                    "type": "string"
                },
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "oshi_color": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "http.swaggerAccountOverviewResponse": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "deletion_request": {
                    "$ref": "#/definitions/http.swaggerDeletionRequest"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "identity_id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "memberships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.swaggerAppMembership"
                    }
                },
                "subject": {
                    "type": "string",
                    "example": "user-123"
                }
            }
        },
        "http.swaggerAppListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.App"
                    }
                }
            }
        },
        "http.swaggerAppMembership": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "app_name": {
                    "type": "string",
                    "example": "Idol Web"
                },
                "app_slug": {
                    "type": "string",
                    "example": "idol-web"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-04-30T00:00:00Z"
                },
                "created_by": {
                    "type": "string",
                    "example": "identity-123"
                },
                "id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "identity_id": {
                    "type": "string",
                    "example": "identity-123"
                },
                "party_type": {
                    "type": "string",
                    "example": "first_party"
                },
                "profile": {
                    "type": "string",
                    "example": "{}"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-04-30T00:00:00Z"
                },
                "updated_by": {
                    "type": "string",
                    "example": "identity-123"
                }
            }
        },
        "http.swaggerAuditLog": {
            "type": "object",
            "properties": {
                "ActorID": {
                    "type": "string",
                    "example": "bootstrap-admin"
                },
                "ActorType": {
                    "type": "string",
                    "example": "admin_client"
                },
                "EventType": {
                    "type": "string",
                    "example": "oidc_client.created"
                },
                "ID": {
                    "type": "string",
                    "example": "4bba3a6f-19ea-4b2d-9341-61eeb31b9cc2"
                },
                "IPAddress": {
                    "type": "string",
                    "example": "192.0.2.1"
                },
                "Metadata": {
                    "type": "string",
                    "example": "{}"
                },
                "OccurredAt": {
                    "type": "string",
                    "example": "2026-04-25T10:05:00Z"
                },
                "RequestID": {
                    "type": "string",
                    "example": "req-123"
                },
                "Result": {
                    "type": "string",
                    "example": "success"
                },
                "TargetID": {
                    "type": "string",
                    "example": "f4e3f55f-bb7a-4787-a4fb-b346b6dc1a82"
                },
                "TargetType": {
                    "type": "string",
                    "example": "client"
                },
                "UserAgent": {
                    "type": "string",
                    "example": "curl/8.7.1"
                }
            }
        },
        "http.swaggerAuditLogListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.swaggerAuditLog"
                    }
                }
            }
        },
        "http.swaggerCreateAppRequest": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/http.swaggerInlineClientCreateRequest"
                },
                "description": {
                    "type": "string",
                    "example": "Internal demo app"
                },
                "name": {
                    "type": "string",
                    "example": "Demo Web App"
                },
                "party_type": {
                    "type": "string",
                    "example": "first_party"
                },
                "post_logout_redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/"
                    ]
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/callback"
                    ]
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "openid",
                        "email"
                    ]
                },
                "slug": {
                    "type": "string",
                    "example": "demo-web"
                },
                "type": {
                    "type": "string",
                    "example": "web"
                }
            }
        },
        "http.swaggerCreateAppResponse": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/app.App"
                },
                "management_token": {
                    "type": "string",
                    "example": "iat_0123456789abcdef"
                }
            }
        },
        "http.swaggerCreateAppWithClientResponse": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/app.App"
                },
                "client": {
                    "$ref": "#/definitions/app.OIDCClient"
                },
                "client_secret": {
                    "type": "string",
                    "example": ""
                },
                "management_token": {
                    "type": "string",
                    "example": "iat_0123456789abcdef"
                }
            }
        },
        "http.swaggerCreateOIDCClientRequest": {
            "type": "object",
            "properties": {
                "client_type": {
                    "type": "string",
                    "example": "public"
                },
                "name": {
                    "type": "string",
                    "example": "Demo Browser Client"
                },
                "post_logout_redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "http://localhost:3002/"
                    ]
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "http://localhost:3002/callback"
                    ]
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "openid",
                        "profile",
                        "email"
                    ]
                },
                "token_endpoint_auth_method": {
                    "type": "string",
                    "example": "none"
                }
            }
        },
        "http.swaggerCreateOIDCClientResponse": {
            "type": "object",
            "properties": {
                "client": {
                    "$ref": "#/definitions/app.OIDCClient"
                },
                "client_secret": {
                    "type": "string",
                    "example": ""
                }
            }
        },
        "http.swaggerDeletionRequest": {
            "type": "object",
            "properties": {
                "cancelled_at": {
                    "type": "string",
                    "example": "2026-05-01T00:00:00Z"
                },
                "completed_at": {
                    "type": "string",
                    "example": "2026-05-07T00:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "identity_id": {
                    "type": "string",
                    "example": "identity-123"
                },
                "last_actor_id": {
                    "type": "string",
                    "example": "identity-123"
                },
                "reason": {
                    "type": "string",
                    "example": "user_requested"
                },
                "requested_at": {
                    "type": "string",
                    "example": "2026-04-30T00:00:00Z"
                },
                "scheduled_for": {
                    "type": "string",
                    "example": "2026-05-07T00:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "scheduled"
                }
            }
        },
        "http.swaggerDeletionRequestEnvelope": {
            "type": "object",
            "properties": {
                "request": {
                    "$ref": "#/definitions/http.swaggerDeletionRequest"
                }
            }
        },
        "http.swaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid json body"
                }
            }
        },
        "http.swaggerIdentity": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "phone": {
                    "type": "string",
                    "example": "09012345678"
                },
                "primary_identifier_type": {
                    "type": "string",
                    "example": "email"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "viewer",
                        "admin"
                    ]
                },
                "schema_id": {
                    "type": "string",
                    "example": "default"
                },
                "state": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "http.swaggerIdentityListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.swaggerIdentity"
                    }
                }
            }
        },
        "http.swaggerInlineClientCreateRequest": {
            "type": "object",
            "properties": {
                "client_type": {
                    "type": "string",
                    "example": "confidential"
                },
                "name": {
                    "type": "string",
                    "example": "Demo Browser Client"
                },
                "post_logout_redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/"
                    ]
                },
                "redirect_uris": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/callback"
                    ]
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "openid",
                        "email"
                    ]
                },
                "token_endpoint_auth_method": {
                    "type": "string",
                    "example": "client_secret_basic"
                }
            }
        },
        "http.swaggerLogoutStartResponse": {
            "type": "object",
            "properties": {
                "logout_url": {
                    "type": "string",
                    "example": "http://localhost:4444/oauth2/sessions/logout"
                }
            }
        },
        "http.swaggerManagementTokenResponse": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "management_token": {
                    "type": "string",
                    "example": "iat_0123456789abcdef"
                }
            }
        },
        "http.swaggerMembershipListResponse": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/app.App"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.swaggerAppMembership"
                    }
                }
            }
        },
        "http.swaggerOIDCClientListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.OIDCClient"
                    }
                }
            }
        },
        "http.swaggerPatchUserRequest": {
            "type": "object",
            "properties": {
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "http.swaggerRolesUpdateResponse": {
            "type": "object",
            "properties": {
                "identity_id": {
                    "type": "string",
                    "example": "8a7b9e7b-0f84-4f54-a7e7-1ef8d8aa4f73"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "admin",
                        "support"
                    ]
                }
            }
        },
        "http.swaggerScheduleDeletionRequest": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "user_requested"
                }
            }
        },
        "http.swaggerStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.swaggerThemePreferenceRequest": {
            "type": "object",
            "properties": {
                "oshi_color": {
                    "type": "string",
                    "example": "#b2b2ff"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "idol-auth API",
	Description:      "Ory Kratos / Hydra をバックエンドにした認証・認可プラットフォームの API です。\n\n- Auth API: Hydra login / consent / logout を仲介するブラウザ向け API\n- Admin API: アプリ登録、OIDC クライアント発行、ユーザー管理、監査ログ取得 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
